In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pingouin as pg
import scipy 
import numpy as np
import string
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [13]:
df = pd.read_excel('./comparison_data_cvs_sorted.xlsx')
df["G1"] = df["G1"].str.strip(string.digits)
df["G2"] = df["G2"].str.strip(string.digits)
# df = df[df["G2"] != "escit"]
# df = df[df["G2"] != "tryp"]
print(np.unique(df["G2"]))
print(df.size)
# label_0 = pg.mixed_anova(dv='Data1', within='G1', between = 'G2', subject = 'Subject', data=df)
label_1 = pg.mixed_anova(dv='Data2', within='G1', between = 'G2', subject = 'Subject', data=df)
label_2 = pg.mixed_anova(dv='Data3', within='G1', between = 'G2', subject = 'Subject', data=df)



(df["Labels"]).value_counts()


['control' 'escit' 'mirt' 'tryp']
297600


0    32178
2     2982
1     2040
Name: Labels, dtype: int64

In [4]:
df

G1       G2 Subject    No     Data1     Data2     Data3  Labels
0      post  control   dish1    n0  0.995666  0.002701  0.001634       0
1      post  control   dish1    n1  0.995672  0.002695  0.001633       0
2      post  control   dish1    n2  0.995702  0.002664  0.001634       0
3      post  control   dish1    n3  0.995717  0.002649  0.001635       0
4      post  control   dish1    n4  0.995697  0.002668  0.001634       0
...     ...      ...     ...   ...       ...       ...       ...     ...
37195   pre  control   dish1  n595  0.995326  0.002415  0.002259       0
37196   pre  control   dish1  n596  0.995121  0.002209  0.002670       0
37197   pre  control   dish1  n597  0.994304  0.001774  0.003922       0
37198   pre  control   dish1  n598  0.982729  0.000915  0.016356       0
37199   pre  control   dish1  n599  0.877059  0.001405  0.121536       0

[37200 rows x 8 columns]

In [5]:
label_1

Source        SS  DF1  DF2        MS         F     p-unc       np2  \
0           G2  0.005266    3    6  0.001755  0.259326  0.852343  0.114780   
1           G1  0.000837    1    6  0.000837  6.556527  0.042876  0.522161   
2  Interaction  0.000138    3    6  0.000046  0.360083  0.784405  0.152572   

   eps  
0  NaN  
1  1.0  
2  NaN

In [6]:
label_2

Source        SS  DF1  DF2        MS         F     p-unc       np2  \
0           G2  0.005726    3    6  0.001909  0.198272  0.893905  0.090194   
1           G1  0.000870    1    6  0.000870  2.600033  0.157988  0.302328   
2  Interaction  0.000479    3    6  0.000160  0.476556  0.710117  0.192427   

   eps  
0  NaN  
1  1.0  
2  NaN

In [12]:
post_hocs_wf = pg.pairwise_tests(dv='Data2', within="G1", subject='Subject', data=df, padjust="bonf")

post_hocs_bf = pg.pairwise_tests(dv='Data2', between = 'G2', subject='Subject', data=df,padjust="bonf", within_first = True)

In [13]:
post_hocs_wf

Contrast     A    B  Paired  Parametric         T  dof alternative  \
0       G1  post  pre    True        True  2.886914  9.0   two-sided   

      p-unc  BF10   hedges  
0  0.017974  3.89  0.24301

In [14]:
p_arr = np.append(post_hocs_wf["p-unc"].to_numpy(), post_hocs_bf["p-unc"].to_numpy())
m_c = pg.multicomp(p_arr)
m_c

(array([ True,  True,  True, False,  True,  True,  True]),
 array([3.59487726e-02, 8.44459466e-21, 1.73687030e-20, 4.38157566e-01,
        2.47034620e-44, 1.42800200e-17, 4.18364889e-06]))

In [15]:
post_hocs_bf

Contrast        A      B  Paired  Parametric          T           dof  \
0       G2  control  escit   False        True  -9.588096   4734.093920   
1       G2  control   mirt   False        True   9.454878  28497.520228   
2       G2  control   tryp   False        True   0.775363   5625.720078   
3       G2    escit   mirt   False        True  14.273171   4238.957216   
4       G2    escit   tryp   False        True   8.714877   7198.000000   
5       G2     mirt   tryp   False        True  -4.831983   4730.376207   

  alternative         p-unc        p-corr p-adjust       BF10    hedges  
0   two-sided  1.407432e-21  8.444595e-21     bonf  1.617e+18 -0.202621  
1   two-sided  3.473741e-21  2.084244e-20     bonf   3.08e+17  0.107931  
2   two-sided  4.381576e-01  1.000000e+00     bonf      0.028  0.013812  
3   two-sided  3.529066e-45  2.117440e-44     bonf  1.808e+42  0.359321  
4   two-sided  3.570005e-18  2.142003e-17     bonf  6.272e+14  0.205390  
5   two-sided  1.394550e-06  8.367298e-06     bonf   2412.809 -0.104795

In [16]:
post_hocs_wf = pg.pairwise_tests(dv='Data3', within="G1", subject='Subject',padjust="bonf", data=df)

post_hocs_bf = pg.pairwise_tests(dv='Data3', between = 'G2', subject='Subject', data=df,padjust="bonf", within_first = False)

In [17]:
post_hocs_wf

Contrast     A    B  Paired  Parametric         T  dof alternative  \
0       G1  post  pre    True        True  1.774704  9.0   two-sided   

      p-unc   BF10    hedges  
0  0.109689  0.988  0.208708

In [18]:
post_hocs_bf

Contrast        A      B  Paired  Parametric          T           dof  \
0       G2  control  escit   False        True -10.897364   4793.682772   
1       G2  control   mirt   False        True   3.772997  29858.494615   
2       G2  control   tryp   False        True   1.565583   5740.629742   
3       G2    escit   mirt   False        True  12.939545   4549.985157   
4       G2    escit   tryp   False        True  10.409790   7198.000000   
5       G2     mirt   tryp   False        True  -0.801395   5295.302314   

  alternative         p-unc        p-corr p-adjust       BF10    hedges  
0   two-sided  2.476102e-27  1.485661e-26     bonf  9.864e+23 -0.226879  
1   two-sided  1.616095e-04  9.696568e-04     bonf     16.001  0.043344  
2   two-sided  1.175014e-01  7.050082e-01     bonf      0.071  0.027441  
3   two-sided  1.232832e-37  7.396993e-37     bonf  2.925e+34  0.294230  
4   two-sided  3.375153e-25  2.025092e-24     bonf   5.42e+21  0.245336  
5   two-sided  4.229388e-01  1.000000e+00     bonf      0.029 -0.015509

In [19]:
p_arr = np.append(post_hocs_wf["p-unc"].to_numpy(), post_hocs_bf["p-unc"].to_numpy())
m_c = pg.multicomp(p_arr)
m_c

(array([False,  True,  True, False,  True,  True, False]),
 array([3.29068207e-01, 1.48566107e-26, 6.46437865e-04, 3.29068207e-01,
        8.62982561e-37, 1.68757671e-24, 4.22938778e-01]))

In [366]:
print(df[(df['G1'] == 'pre')].mean())
print(df[(df['G1'] == 'pre')].std())

Data1     0.865736
Data2     0.056151
Data3     0.078113
Labels    0.191989
dtype: float64
Data1     0.238179
Data2     0.159322
Data3     0.197971
Labels    0.547610
dtype: float64


In [367]:
print(df[(df['G1'] == 'post')].mean())
print(df[(df['G1'] == 'post')].std())

Data1     0.840347
Data2     0.068786
Data3     0.090867
Labels    0.238333
dtype: float64
Data1     0.256567
Data2     0.176987
Data3     0.214222
Labels    0.597883
dtype: float64


In [390]:
print(df[(df['G2'] == 'control')].mean())
print(df[(df['G2'] == 'control')].std())

Data1     0.850845
Data2     0.065640
Data3     0.083515
Labels    0.225897
dtype: float64
Data1     0.261362
Data2     0.180916
Data3     0.213256
Labels    0.581128
dtype: float64


In [391]:
print(df[(df['G2'] == 'escit')].mean())
print(df[(df['G2'] == 'escit')].std())

Data1     0.761921
Data2     0.104109
Data3     0.133970
Labels    0.386389
dtype: float64
Data1     0.301566
Data2     0.224494
Data3     0.258224
Labels    0.718418
dtype: float64


In [392]:
print(df[(df['G2'] == 'mirt')].mean())
print(df[(df['G2'] == 'mirt')].std())

Data1     0.876691
Data2     0.048449
Data3     0.074861
Labels    0.163750
dtype: float64
Data1     0.211484
Data2     0.131884
Data3     0.183781
Labels    0.518555
dtype: float64


In [393]:
print(df[(df['G2'] == 'tryp')].mean())
print(df[(df['G2'] == 'tryp')].std())

Data1     0.859083
Data2     0.063167
Data3     0.077749
Labels    0.203056
dtype: float64
Data1     0.241779
Data2     0.170455
Data3     0.195770
Labels    0.553492
dtype: float64


In [369]:
print(df[(df['G2'] == 'control') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') & (df['G1'] == 'pre')].std())

Data1     0.864539
Data2     0.058764
Data3     0.076697
Labels    0.204615
dtype: float64
Data1     0.252197
Data2     0.171042
Data3     0.205849
Labels    0.559275
dtype: float64


In [370]:
print(df[(df['G2'] == 'escit') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'escit') & (df['G1'] == 'pre')].std())

Data1     0.758624
Data2     0.100887
Data3     0.140489
Labels    0.402222
dtype: float64
Data1     0.306440
Data2     0.226700
Data3     0.262776
Labels    0.731561
dtype: float64


In [371]:
print(df[(df['G2'] == 'escit') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'escit') & (df['G1'] == 'post')].std())

Data1     0.765219
Data2     0.107330
Data3     0.127451
Labels    0.370556
dtype: float64
Data1     0.296662
Data2     0.222282
Data3     0.253495
Labels    0.704878
dtype: float64


In [372]:
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'pre')].std())

Data1     0.861432
Data2     0.063385
Data3     0.075183
Labels    0.203333
dtype: float64
Data1     0.238374
Data2     0.164301
Data3     0.196137
Labels    0.557719
dtype: float64


In [373]:
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'post')].std())

Data1     0.856734
Data2     0.062949
Data3     0.080316
Labels    0.202778
dtype: float64
Data1     0.245181
Data2     0.176440
Data3     0.195423
Labels    0.549388
dtype: float64


In [374]:
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'pre')].std())

Data1     0.894886
Data2     0.040328
Data3     0.064786
Labels    0.122917
dtype: float64
Data1     0.190440
Data2     0.116301
Data3     0.165308
Labels    0.456500
dtype: float64


In [375]:
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'post')].std())

Data1     0.858495
Data2     0.056569
Data3     0.084936
Labels    0.204583
dtype: float64
Data1     0.229189
Data2     0.145367
Data3     0.200064
Labels    0.571058
dtype: float64


In [378]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'pre')].std())

Data1     0.841305
Data2     0.069286
Data3     0.089409
Labels    0.244138
dtype: float64
Data1     0.267846
Data2     0.186477
Data3     0.219577
Labels    0.600826
dtype: float64


In [379]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'post')].std())

Data1     0.841987
Data2     0.069953
Data3     0.088060
Labels    0.240862
dtype: float64
Data1     0.266501
Data2     0.186050
Data3     0.218166
Labels    0.596730
dtype: float64


In [380]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'pre')].std())

Data1     0.864753
Data2     0.057647
Data3     0.077600
Labels    0.193377
dtype: float64
Data1     0.242091
Data2     0.163718
Data3     0.199551
Labels    0.546949
dtype: float64


In [381]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'post')].std())

Data1     0.853261
Data2     0.062775
Data3     0.083964
Labels    0.219167
dtype: float64
Data1     0.251667
Data2     0.170541
Data3     0.209177
Labels    0.578040
dtype: float64


In [382]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'pre')].std())

Data1     0.851941
Data2     0.065407
Data3     0.082653
Labels    0.223563
dtype: float64
Data1     0.259092
Data2     0.179266
Data3     0.211559
Labels    0.578776
dtype: float64


In [383]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'post')].std())

Data1     0.851455
Data2     0.065361
Data3     0.083184
Labels    0.223506
dtype: float64
Data1     0.259734
Data2     0.180455
Data3     0.211478
Labels    0.577953
dtype: float64
