In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pingouin as pg
import scipy 
import numpy as np
import string
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_excel('./comparison_data_5s.xlsx')
df["G1"] = df["G1"].str.strip(string.digits)
df["G2"] = df["G2"].str.strip(string.digits)
# df = df[df["G2"] != "escit"]
# df = df[df["G2"] != "tryp"]
print(np.unique(df["G2"]))
print(df.size)
# label_0 = pg.mixed_anova(dv='Data1', within='G1', between = 'G2', subject = 'Subject', data=df)
label_1 = pg.mixed_anova(dv='Data2', within='G1', between = 'G2', subject = 'Subject', data=df)
label_2 = pg.mixed_anova(dv='Data3', within='G1', between = 'G2', subject = 'Subject', data=df)



(df["Labels"]).value_counts()


['control' 'escit' 'mirt' 'tryp']
5952


0    429
2    163
1    152
Name: Labels, dtype: int64

In [6]:
df

G1       G2 Subject   No     Data1     Data2     Data3  Labels
0    post  control   dish1   n0  0.895670  0.066421  0.037909       0
1    post  control   dish1   n1  0.725595  0.140567  0.133838       0
2    post  control   dish1   n2  0.560608  0.099550  0.339842       0
3    post  control   dish1   n3  0.595494  0.377833  0.026673       0
4    post  control   dish1   n4  0.212893  0.052990  0.734117       2
..    ...      ...     ...  ...       ...       ...       ...     ...
739   pre  control   dish1   n7  0.835324  0.057724  0.106952       0
740   pre  control   dish1   n8  0.207653  0.088188  0.704159       2
741   pre  control   dish1   n9  0.168536  0.806918  0.024546       1
742   pre  control   dish1  n10  0.464142  0.022148  0.513710       2
743   pre  control   dish1  n11  0.552081  0.255366  0.192554       0

[744 rows x 8 columns]

In [7]:
label_1

Source        SS  DF1  DF2        MS         F     p-unc       np2  \
0           G2  0.016401    3    6  0.005467  0.328382  0.805520  0.141034   
1           G1  0.000282    1    6  0.000282  0.224128  0.652646  0.036010   
2  Interaction  0.000394    3    6  0.000131  0.104529  0.954407  0.049669   

   eps  
0  NaN  
1  1.0  
2  NaN

In [8]:
label_2

Source        SS  DF1  DF2        MS         F     p-unc       np2  \
0           G2  0.011140    3    6  0.003713  0.291776  0.830239  0.127314   
1           G1  0.008038    1    6  0.008038  2.538191  0.162230  0.297275   
2  Interaction  0.003609    3    6  0.001203  0.379834  0.771419  0.159605   

   eps  
0  NaN  
1  1.0  
2  NaN

In [9]:
post_hocs_wf = pg.pairwise_tests(dv='Data2', within="G1", subject='Subject', data=df, padjust="bonf")

post_hocs_bf = pg.pairwise_tests(dv='Data2', between = 'G2', subject='Subject', data=df,padjust="bonf", within_first = True)

In [10]:
post_hocs_wf

Contrast     A    B  Paired  Parametric         T  dof alternative  \
0       G1  post  pre    True        True  0.565238  9.0   two-sided   

      p-unc   BF10    hedges  
0  0.585724  0.354  0.086569

In [11]:
p_arr = np.append(post_hocs_wf["p-unc"].to_numpy(), post_hocs_bf["p-unc"].to_numpy())
m_c = pg.multicomp(p_arr)
m_c

(array([False, False, False, False, False, False, False]),
 array([1.        , 0.39394073, 1.        , 0.67777285, 0.26948768,
        0.10098172, 0.86752983]))

In [12]:
post_hocs_bf

Contrast        A      B  Paired  Parametric         T         dof  \
0       G2  control  escit   False        True -1.777159   93.667629   
1       G2  control   mirt   False        True  0.480478  597.274964   
2       G2  control   tryp   False        True  1.381825  127.428354   
3       G2    escit   mirt   False        True  2.033702   90.353471   
4       G2    escit   tryp   False        True  2.476919  142.000000   
5       G2     mirt   tryp   False        True  1.064684  118.880244   

  alternative     p-unc    p-corr p-adjust   BF10    hedges  
0   two-sided  0.078788  0.472729     bonf  0.632 -0.264229  
1   two-sided  0.631063  1.000000     bonf  0.102  0.039033  
2   two-sided  0.169443  1.000000     bonf  0.351  0.157180  
3   two-sided  0.044915  0.269488     bonf  1.006  0.323824  
4   two-sided  0.014426  0.086556     bonf  2.874  0.410636  
5   two-sided  0.289177  1.000000     bonf  0.246  0.131343

In [13]:
post_hocs_wf = pg.pairwise_tests(dv='Data3', within="G1", subject='Subject',padjust="bonf", data=df)

post_hocs_bf = pg.pairwise_tests(dv='Data3', between = 'G2', subject='Subject', data=df,padjust="bonf", within_first = False)

In [14]:
post_hocs_wf

Contrast     A    B  Paired  Parametric         T  dof alternative  \
0       G1  post  pre    True        True  1.788749  9.0   two-sided   

      p-unc   BF10    hedges  
0  0.107283  1.003  0.490991

In [15]:
post_hocs_bf

Contrast        A      B  Paired  Parametric         T         dof  \
0       G2  control  escit   False        True -1.583990   98.670355   
1       G2  control   mirt   False        True -0.801461  596.836895   
2       G2  control   tryp   False        True  1.175620  130.057477   
3       G2    escit   mirt   False        True  1.136215   98.838582   
4       G2    escit   tryp   False        True  2.202103  142.000000   
5       G2     mirt   tryp   False        True  1.766791  130.215357   

  alternative     p-unc    p-corr p-adjust   BF10    hedges  
0   two-sided  0.116396  0.698376     bonf  0.466 -0.222085  
1   two-sided  0.423184  1.000000     bonf  0.125 -0.065315  
2   two-sided  0.241894  1.000000     bonf  0.274  0.132002  
3   two-sided  0.258614  1.000000     bonf  0.264  0.163533  
4   two-sided  0.029271  0.175628     bonf  1.617  0.365075  
5   two-sided  0.079606  0.477637     bonf  0.625  0.205379

In [16]:
p_arr = np.append(post_hocs_wf["p-unc"].to_numpy(), post_hocs_bf["p-unc"].to_numpy())
m_c = pg.multicomp(p_arr)
m_c

(array([False, False, False, False, False, False, False]),
 array([0.53641465, 0.53641465, 0.72568335, 0.72568335, 0.72568335,
        0.20489958, 0.47763721]))

In [17]:
print(df[(df['G1'] == 'pre')].mean())
print(df[(df['G1'] == 'pre')].std())

Data1     0.532354
Data2     0.237116
Data3     0.230530
Labels    0.583333
dtype: float64
Data1     0.276633
Data2     0.262270
Data3     0.259503
Labels    0.791492
dtype: float64


In [18]:
print(df[(df['G1'] == 'post')].mean())
print(df[(df['G1'] == 'post')].std())

Data1     0.486397
Data2     0.243793
Data3     0.269810
Labels    0.701613
dtype: float64
Data1     0.284439
Data2     0.279188
Data3     0.287111
Labels    0.840163
dtype: float64


In [19]:
print(df[(df['G2'] == 'control')].mean())
print(df[(df['G2'] == 'control')].std())

Data1     0.518409
Data2     0.241083
Data3     0.240508
Labels    0.612179
dtype: float64
Data1     0.290576
Data2     0.278838
Data3     0.279243
Labels    0.806074
dtype: float64


In [20]:
print(df[(df['G2'] == 'escit')].mean())
print(df[(df['G2'] == 'escit')].std())

Data1     0.377475
Data2     0.318405
Data3     0.304121
Labels    0.875000
dtype: float64
Data1     0.297982
Data2     0.344026
Data3     0.313251
Labels    0.821155
dtype: float64


In [21]:
print(df[(df['G2'] == 'mirt')].mean())
print(df[(df['G2'] == 'mirt')].std())

Data1     0.510801
Data2     0.230737
Data3     0.258462
Labels    0.684028
dtype: float64
Data1     0.264345
Data2     0.248520
Data3     0.269357
Labels    0.843600
dtype: float64


In [22]:
print(df[(df['G2'] == 'tryp')].mean())
print(df[(df['G2'] == 'tryp')].std())

Data1     0.596427
Data2     0.198654
Data3     0.204920
Labels    0.375000
dtype: float64
Data1     0.247727
Data2     0.223471
Data3     0.219059
Labels    0.680462
dtype: float64


In [23]:
print(df[(df['G2'] == 'control') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') & (df['G1'] == 'pre')].std())

Data1     0.557955
Data2     0.233350
Data3     0.208695
Labels    0.532051
dtype: float64
Data1     0.281920
Data2     0.264340
Data3     0.253486
Labels    0.765547
dtype: float64


In [24]:
print(df[(df['G2'] == 'escit') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'escit') & (df['G1'] == 'pre')].std())

Data1     0.395578
Data2     0.318267
Data3     0.286155
Labels    0.750000
dtype: float64
Data1     0.311430
Data2     0.344527
Data3     0.308703
Labels    0.806226
dtype: float64


In [25]:
print(df[(df['G2'] == 'escit') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'escit') & (df['G1'] == 'post')].std())

Data1     0.359372
Data2     0.318542
Data3     0.322086
Labels    1.000000
dtype: float64
Data1     0.287161
Data2     0.348411
Data3     0.321084
Labels    0.828079
dtype: float64


In [26]:
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'pre')].std())

Data1     0.588330
Data2     0.196703
Data3     0.214968
Labels    0.416667
dtype: float64
Data1     0.227375
Data2     0.213325
Data3     0.229138
Labels    0.731925
dtype: float64


In [27]:
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'tryp') & (df['G1'] == 'post')].std())

Data1     0.604524
Data2     0.200605
Data3     0.194871
Labels    0.333333
dtype: float64
Data1     0.269548
Data2     0.236200
Data3     0.211264
Labels    0.632456
dtype: float64


In [28]:
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'pre')].std())

Data1     0.524818
Data2     0.231012
Data3     0.244170
Labels    0.638889
dtype: float64
Data1     0.264061
Data2     0.245776
Data3     0.259503
Labels    0.824546
dtype: float64


In [29]:
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'mirt') & (df['G1'] == 'post')].std())

Data1     0.496783
Data2     0.230462
Data3     0.272755
Labels    0.729167
dtype: float64
Data1     0.264804
Data2     0.252092
Data3     0.279034
Labels    0.862739
dtype: float64


In [30]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'pre')].std())

Data1     0.505702
Data2     0.249067
Data3     0.245230
Labels    0.626437
dtype: float64
Data1     0.294721
Data2     0.286725
Data3     0.282299
Labels    0.806023
dtype: float64


In [31]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'escit') & (df['G1'] == 'post')].std())

Data1     0.501957
Data2     0.249096
Data3     0.248947
Labels    0.652299
dtype: float64
Data1     0.293844
Data2     0.287205
Data3     0.284437
Labels    0.815781
dtype: float64


In [32]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'pre')].std())

Data1     0.520433
Data2     0.237902
Data3     0.241665
Labels    0.620614
dtype: float64
Data1     0.282198
Data2     0.268609
Data3     0.272884
Labels    0.811140
dtype: float64


In [33]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'mirt') & (df['G1'] == 'post')].std())

Data1     0.511580
Data2     0.237729
Data3     0.250691
Labels    0.649123
dtype: float64
Data1     0.282580
Data2     0.270447
Data3     0.279274
Labels    0.825233
dtype: float64


In [34]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'pre')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'pre')].std())

Data1     0.525642
Data2     0.236492
Data3     0.237866
Labels    0.591954
dtype: float64
Data1     0.285208
Data2     0.272870
Data3     0.274305
Labels    0.799959
dtype: float64


In [35]:
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'post')].mean())
print(df[(df['G2'] == 'control') | (df['G2'] == 'tryp') & (df['G1'] == 'post')].std())

Data1     0.527317
Data2     0.236895
Data3     0.235787
Labels    0.583333
dtype: float64
Data1     0.289297
Data2     0.274707
Data3     0.273098
Labels    0.793677
dtype: float64
